version: 2.1

jobs:
  quality: &test-template
    docker:
      - image: python:3.8
    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: style
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox

  py38-fast:
    <<: *test-template
    environment:
      TOXENV: tests38-fast

  py38-online:
    <<: *test-template
    environment:
      TOXENV: tests38-online

  py38-slow:
    <<: *test-template
    environment:
      TOXENV: tests38-slow

  py38-images:
    <<: *test-template
    environment:
      TOXENV: tests38-images

  py38-coverage:
    <<: *test-template
    environment:
      TOXENV: tests38-coverage
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox
      - run: python -m pip install codecov && codecov

  py39:
    <<: *test-template
    docker:
      - image: python:3.9
    environment:
      TOXENV: tests39

  py310:
    <<: *test-template
    docker:
      - image: python:3.10
    environment:
      TOXENV: tests310

  py311:
    <<: *test-template
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - tests38-fast:
          requires:
            - quality
      - tests38-online:
          requires:
            - quality
      - tests38-slow:
          requires:
            - quality
      - tests38-images:
          requires:
            - quality
      - tests38-coverage:
          requires:
            - quality
      - tests39:
          requires:
            - quality
      - tests310:
          requires:
            - quality
      - tests311:
          requires:
            - quality
