version: 2.1

jobs:
  quality: &test-template
    description: Code style
    docker:
      - image: python:3.10
    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: style
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox

  tests38:
    <<: *test-template
    description: Tests - Python 3.8
    docker:
      - image: python:3.8
    environment:
      TOXENV: tests38

  tests39:
    <<: *test-template
    description: Tests - Python 3.9
    docker:
      - image: python:3.9
    environment:
      TOXENV: tests39

  tests310:
    <<: *test-template
    description: Tests - Python 3.10
    docker:
      - image: python:3.10
    environment:
      TOXENV: tests310

  tests311:
    <<: *test-template
    description: Tests - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311

  tests311-fast:
    <<: *test-template
    description: Tests fast - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311-fast

  tests311-online:
    <<: *test-template
    description: Tests online - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311-online

  tests311-slow:
    <<: *test-template
    description: Tests slow - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311-slow

  tests311-images:
    <<: *test-template
    description: Tests images - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311-images

  tests311-coverage:
    <<: *test-template
    description: Tests coverage - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311-coverage
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox
      - run: python -m pip install codecov && codecov

  tests312:
    <<: *test-template
    description: Tests - Python 3.12
    docker:
      - image: python:3.12
    environment:
      TOXENV: tests312

  tests313:
    <<: *test-template
    description: Tests - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313


workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - tests38:
          requires:
            - quality
      - tests39:
          requires:
            - quality
      - tests310:
          requires:
            - quality
      - tests311:
          requires:
            - quality
      - tests311-fast:
          requires:
            - quality
      - tests311-online:
          requires:
            - quality
      - tests311-slow:
          requires:
            - quality
      - tests311-images:
          requires:
            - quality
      - tests311-coverage:
          requires:
            - quality
      - tests312:
          requires:
            - quality
      - tests313:
          requires:
            - quality
