# This workflow triggers boinor/validation CI from boinor/boinor
# everytime a new commit is introduced in boinor:main branch
name: Validation test cases

on:
  # A collection of events which trigger the validation action
  push:
    branches: [ main, actions ]
  release:

  # Enable manually to execute the actions
  workflow_dispatch:

jobs:
  
  # Validate boinor's new features
  validation:
    runs-on: ubuntu-latest
    environment: validation-env

    # Steps to be followed during validation job
    steps:
      - name: Trigger boinor/validation
        run: |
          curl -XPOST -u "${{ secrets.VALIDATION_TOKEN_LOGIN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/boinor/validation/actions/workflows/158547455/dispatches \
          --data '{"ref": "main"}' \
          --fail
